### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by tbergen1** [JHK3746/sql-scratch-capstone-turn-in#1]
### Criteria 1: Report
* **Score Level**: 4/4 (Exceeds Expectations)
* *Comment(s)*: Your slides are well done.  They have a nice, clean design which makes them nice to look at.  Also, you included all the major parts for each answer: the result, an explanation of that result, and the query that generated the result.  I loved your inclusion of graphs and other charts to make it easy to digest the data you received from your queries.  Great job!

### Criteria 2: Query Accuracy
* **Score Level**: 4/4 (Exceeds Expectations)
* *Comment(s)*: All queries accurately retrieve the data intended.  Great job!

### Criteria 3: Query Formatting
* **Score Level**: 3/4 (Meets Expectations)
* *Comment(s)*: Queries adhere to most of the rules of the style guide.  There were some indentation issue, mainly around indenting column names when listing them within SELECT statements.  Other than that, great job!

### Criteria 4: Understanding underlying concepts and terminology
* **Score Level**: 4/4 (Exceeds Expectations)
* *Comment(s)*: Your report demonstrated an understanding of the concepts of attribution.  You provided good insight into what attribution analysis is used for as well as what business insights can be gleaned from its application.  You also gave good advice to the company regarding what course it should take when reinvesting based on evidence derived from your queries.  Awesome!

### Overall Score: 15/16
Overall, you did a great job with this.  You demonstrated clear understanding of the material and developed a good looking, clean report on your findings.  All of your conclusions were supported with evidence coming from well-formatted, accurate queries.  Keep up the good work!

**Comment by JHK3746** [comment]
Thank you so much for your fruitful feedback, Tom!!!! I really appreciate it :-)
